java17:
  id: java17
  applications:
        - java:17
        - maven:3.9.6
        - eclipse-jee:2024-03
  autoinstallapps: true
  displayname: "Java 17"
java22:
  id: java12
  applications:
        - java:22
        - maven:3.9.6
        - eclipse-jee:2024-03
  autoinstallapps: true
  displayname: "Java 22"
ml:
  id: ml
  CheckVirtualEnv: true
  applications:
        - python:3.12
  autoinstallapps: true
  displayname: MachineLearning
        